### ISSUE TITLE
難しいかもしれません

### ISSUE THREAD

**Issue by Jawaraisen** [MijinkoSD/FANBOX-downloader.py#3]
Python、コマンドプロンプトどっちで実行すればいいのかわかりません 申し訳ございませんが初心者向けに説明してくれると助かります

**Comment by Mijikko** [comment]
こんにちは。
コマンドプロンプトということはお使いの環境はWindowsでしょうか。
ご自身の環境を可能な限り記載していただけますと助かります。

Windows 10以上の環境であるということを仮定してお答えしますが、以下の順で実行できると思います。
1. Microsoft Storeで[Python3.10](https://www.microsoft.com/store/productId/9PJPW5LDXLZ5?ocid=pdpshare)をダウンロードする。
2. PowerShellを開く。
3. 以下のコマンドを実行する。
    ```sh
    python3.10 main.py <クリエイターID>
    ```

詳細は[README.md](https://github.com/MijinkoSD/FANBOX-downloader.py/blob/main/README.md)にも記載しておりますので、そちらをご確認ください。

ここまでで基本的な使い方をご説明しましたが、このスクリプトはあまり初心者向きではないです。
（コマンドで実行する必要がある、取得したデータは整形されていない、等）
なので、ただ画像などをローカルで楽しみたいだけでしたら、別の方が作成したツールを使用されることをおすすめします。
- [aznhe21/fanboxed: Fanbox Downloader](https://github.com/aznhe21/fanboxed)
- [furubarug/fanbox-downloader: pixiv FANBOXの投稿を投稿毎にフォルダ分け → ZIPとして一括ダウンロードするブックマークレット](https://github.com/furubarug/fanbox-downloader)

上記ツールはブラウザ上で直接実行できるはずなので、ここのスクリプトよりは導入難易度が低いと思われます。
（こちらの方で動作確認は行っておりませんので、その点はご了承ください）

**Comment by Mijikko** [comment]
初回起動時は環境構築が必要なことを失念しておりました。

上記の手順2と3の間に以下のコマンドを実行してください。
```sh
python3.10 -m pip install -r requirements.txt
```

**Comment by Jawaraisen** [comment]
ほとんどわかりました。
windows10 64bitを使用しています。
もっとデータのダウンロード➔最終確認まで教えてくださると助かります

**Comment by Mijikko** [comment]
データのダウンロードは上記のコマンドを入力すればできます。
ダウンロードしたデータは、`posts/<クリエイターID>/<投稿ID>/`の中に入っているはずです。

- `images`は画像データ
- `post`は投稿データ（JSON形式）
- `thumbnails`はサムネイルデータ

です。

申し訳ありませんが、私はもう既にこのリポジトリを使用しておらず開発もしていないため、詳細についてはご自身でお調べいただきますようお願いいたします。
JSON形式の投稿データについては、FANBOX内部で使用されているデータをそのまま保存しているため、整形されておらず読みづらいです。（仕様です）

**Comment by Jawaraisen** [comment]
有料プランの投稿をダウンロードする方法を教えてください、あとユーザーIDはどこの部分ですか？
すみませんが画像で表してくれると助かります

**Comment by Jawaraisen** [comment]
有料プランのデータダウンロード方法を教えてくれると助かります。

**Comment by Mijikko** [comment]
@Jawaraisen 

[README.md](../blob/main/README.md)は熟読されましたでしょうか。
まずはREADME.mdをお読みになられた上で、わからなかった部分は具体的にご質問いただけますと助かります。

有料プランのダウンロードには、README.mdに記載されている通り「cookieのFANBOXSESSIDの値」を取得する必要があります。
cookieの値はブラウザのDevToolsを用いて取得してください。

## FANBOXSESSIDの取得方法
1. PC版のChromeやMicrosoft EdgeなどでFANBOXを開き、ログインします。
2. F12キーを押下してDevTools（開発者向けツール）を開きます。
3. アプリケーションタブ（英語ならApplication）を開きます。
4. 左側の一覧から、「ストレージ」 > 「Cookie」 > 「https:\/\/www.fanbox.cc」を開きます。
5. 以下のように「FANBOXSESSID」がありますので、それをコピーしてください。
    <img width="671" alt="image" src="https://github.com/user-attachments/assets/48b97e56-79c0-4f02-857b-ad0fe4ccfe0f">
6. あとはREADME.mdの「使い方」に従ってコマンドにセッションIDを渡して実行してください。

## セッションIDの注意点【重要！！！】
ここで一度、セッションIDの危険性についてご説明します。
セッションIDは、それ単体であなたのアカウントに完全アクセスできる危険なものとなります。（セッションIDさえ知っていればメールアドレスやパスワードを知らずともアカウントにログインできます）
第三者に知られてしまうとあなたのアカウントに紐づけられた支払い情報（クレジットカードなど）を悪用されますので、セッションIDはたとえご家族やご友人であっても**絶対に共有しないでください！**

なお、アカウントにアクセスされるという危険性においては、ブラウザ拡張機能タイプのFANBOXダウンローダーも同様となります。
そのためいずれのツールであっても、危険性を熟知した上で利用するようにしてください。

**Comment by Jawaraisen** [comment]
sessidはわかったんですが ''>pip update''とか出てきてエラーも発生したから、もう一度最初から説明してくれませんか

**Comment by Mijikko** [comment]
@Jawaraisen 
「エラーが出た」という情報のみではこちらも対応できかねます。

最低限、
- どのような操作を行って（操作手順）
- どのようなエラーが発生したのか（エラー内容の全文）
をご説明ください。

**Comment by Jawaraisen** [comment]
も

**Comment by Jawaraisen** [comment]
申し訳ございませんが理由がわからなくなったので終了させていただきます

**Comment by Jawaraisen** [comment]
python 3.10.2をインストールしています
''Filenotfounderror: no such files or directory''から始まるエラーが発生しました
ちなみにwindows 10 64bitを使用しています。

**Comment by Jawaraisen** [comment]
まず試しに''2と3のところ''をやっていました。
あとrequirement.txtというファイルが見つかりませんでした。何か変更する箇所があるのでしょうか

**Comment by Mijikko** [comment]
@Jawaraisen 
`requirements.txt`はこれです：https://github.com/MijinkoSD/FANBOX-downloader.py/blob/main/requirements.txt
